### ISSUE TITLE
ImportError: cannot import name 'get_dataset' from partially initialized module 'llama_recipes.datasets.grammar_dataset.grammar_dataset' (most likely due to a circular import)

### ISSUE THREAD

**Issue by FrankGonzalez07** [meta-llama/llama-recipes#401]
### System Info

torch                     2.1.0

cuda:
---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti     Off | 00000000:03:00.0 Off |                  N/A |
|  0%   40C    P8              22W / 350W |    430MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1532    C+G   ...libexec/gnome-remote-desktop-daemon      251MiB |
|    0   N/A  N/A     55074    C+G   ...seed-version=20231214-180149.265000      151MiB |
+---------------------------------------------------------------------------------------+

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When I run:
```python
python /home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/finetuning.py  --use_peft --peft_method lora --quantization --model_name /home/easyai/Projects/17_LLM_projects/llama_7b_deploy_linux/models_hf/7B --output_dir /home/easyai/Projects/17_LLM_projects/llama_7b_deploy_linux/PEFT/7B
``` 

The following errors came out:
```
/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/finetuning.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging
Traceback (most recent call last):
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/finetuning.py", line 32, in <module>
    from llama_recipes.utils import fsdp_auto_wrap_policy
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/utils/__init__.py", line 5, in <module>
    from llama_recipes.utils.dataset_utils import *
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/utils/dataset_utils.py", line 10, in <module>
    from llama_recipes.datasets import (
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/__init__.py", line 4, in <module>
    from llama_recipes.datasets.grammar_dataset.grammar_dataset import get_dataset as get_grammar_dataset
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/grammar_dataset/grammar_dataset.py", line 8, in <module>
    from datasets import load_dataset
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/__init__.py", line 4, in <module>
    from llama_recipes.datasets.grammar_dataset.grammar_dataset import get_dataset as get_grammar_dataset
ImportError: cannot import name 'get_dataset' from partially initialized module 'llama_recipes.datasets.grammar_dataset.grammar_dataset' (most likely due to a circular import) (/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/grammar_dataset/grammar_dataset.py)
``` 

Can anyone help me!

### Error logs

/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/finetuning.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging
Traceback (most recent call last):
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/finetuning.py", line 32, in <module>
    from llama_recipes.utils import fsdp_auto_wrap_policy
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/utils/__init__.py", line 5, in <module>
    from llama_recipes.utils.dataset_utils import *
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/utils/dataset_utils.py", line 10, in <module>
    from llama_recipes.datasets import (
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/__init__.py", line 4, in <module>
    from llama_recipes.datasets.grammar_dataset.grammar_dataset import get_dataset as get_grammar_dataset
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/grammar_dataset/grammar_dataset.py", line 8, in <module>
    from datasets import load_dataset
  File "/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/__init__.py", line 4, in <module>
    from llama_recipes.datasets.grammar_dataset.grammar_dataset import get_dataset as get_grammar_dataset
ImportError: cannot import name 'get_dataset' from partially initialized module 'llama_recipes.datasets.grammar_dataset.grammar_dataset' (most likely due to a circular import) (/home/easyai/Projects/17_LLM_projects/llama-recipes/src/llama_recipes/datasets/grammar_dataset/grammar_dataset.py)

### Expected behavior

I would like to finetune successfully.

**Comment by HamidShojanazeri** [comment]
hi @FrankGonzalez07 can you please [install from src ](https://github.com/meta-llama/llama-recipes#install-from-source)to see if that helps, this feature not present in binaries. We also did a recent refactor pls make sure to [pull the latest](https://github.com/meta-llama/llama-recipes#llama-recipes-examples-to-get-started-using-the-llama-models-from-meta).

**Comment by FrankGonzalez07** [comment]
> hi @FrankGonzalez07 can you please [install from src ](https://github.com/meta-llama/llama-recipes#install-from-source)to see if that helps, this feature not present in binaries. We also did a recent refactor pls make sure to [pull the latest](https://github.com/meta-llama/llama-recipes#llama-recipes-examples-to-get-started-using-the-llama-models-from-meta).

Yes I am sure I pulled the latest one, in which the git log shows:
```
commit c8f4bdac4107856e204b281e4fb611dc4e2de5dc (origin/main, origin/HEAD, main)
Merge: 95418fc eb4a0bb
Author: Hamid Shojanazeri <hamid.nazeri2010@gmail.com>
Date:   Fri Mar 15 10:42:18 2024 -0700

    Adding open in colab option for notebook (#395)
```

**Comment by FrankGonzalez07** [comment]
> hi @FrankGonzalez07 can you please [install from src ](https://github.com/meta-llama/llama-recipes#install-from-source)to see if that helps, this feature not present in binaries. We also did a recent refactor pls make sure to [pull the latest](https://github.com/meta-llama/llama-recipes#llama-recipes-examples-to-get-started-using-the-llama-models-from-meta).

I have tried the advices you provided, but still the same error...

**Comment by HamidShojanazeri** [comment]
I see the issue is you are using ` llama-recipes/src/llama_recipes/finetuning.py` which is part of library src code, can you please run`python recipes/finetuning/finetuning.py` instead? that should solve the issue.

**Comment by KysonYang001** [comment]
> 我看到问题是您正在使用库 src 代码的一部分，您可以运行吗？这应该可以解决问题。您也可以参考此[文档](https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/singlegpu_finetuning.md)` llama-recipes/src/llama_recipes/finetuning.py``python recipes/finetuning/finetuning.py`

Why am I getting this error when I run this file?

`Error while finding module specification for 'finetuning.py' (ModuleNotFoundError: __path__ attribute not found on 'finetuning' while trying to find 'finetuning.py')
`

**Comment by bkhanal-11** [comment]
> > 我看到问题是您正在使用库 src 代码的一部分，您可以运行吗？这应该可以解决问题。您也可以参考此[文档](https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/singlegpu_finetuning.md)``  llama-recipes/src/llama_recipes/finetuning.py``python recipes/finetuning/finetuning.py ``
> 
> Why am I getting this error when I run this file?
> 
> `Error while finding module specification for 'finetuning.py' (ModuleNotFoundError: __path__ attribute not found on 'finetuning' while trying to find 'finetuning.py') `

same

**Comment by HamidShojanazeri** [comment]
@bkhanal-11 I wonder if you have [installed from src](https://github.com/meta-llama/llama-recipes/tree/main#install-from-source)? and pulled the latest?

**Comment by bkhanal-11** [comment]
> @bkhanal-11 I wonder if you have [installed from src](https://github.com/meta-llama/llama-recipes/tree/main#install-from-source)? and pulled the latest?

@HamidShojanazeri I followed the exact instruction in the link, but still getting the same error.

**Comment by KysonYang001** [comment]
> > @bkhanal-11 I wonder if you have [installed from src](https://github.com/meta-llama/llama-recipes/tree/main#install-from-source)? and pulled the latest?
> 
> @HamidShojanazeri I followed the exact instruction in the link, but still getting the same error.

Hi，
Have you solved the problem?

**Comment by bkhanal-11** [comment]
@HamidShojanazeri I am now getting this error when I tried to run from `llama-recipes/recipes/finetuning/finetuning.py`
```bash
/root/llama2_finetuning/llvenv/bin/python3: Error while finding module specification for 'finetuning.py' (ModuleNotFoundError: __path__ attribute not found on 'finetuning' while trying to find 'finetuning.py')
```

**Comment by bkhanal-11** [comment]
> > > @bkhanal-11 I wonder if you have [installed from src](https://github.com/meta-llama/llama-recipes/tree/main#install-from-source)? and pulled the latest?
> > 
> > 
> > @HamidShojanazeri I followed the exact instruction in the link, but still getting the same error.
> 
> Hi， Have you solved the problem?

nope, still stuck with some error

**Comment by bkhanal-11** [comment]
> > > @bkhanal-11 I wonder if you have [installed from src](https://github.com/meta-llama/llama-recipes/tree/main#install-from-source)? and pulled the latest?
> > 
> > 
> > @HamidShojanazeri I followed the exact instruction in the link, but still getting the same error.
> 
> Hi， Have you solved the problem?

Yeah, I removed `-m` from the instruction code and that seems to have solved the problem.

**Comment by KysonYang001** [comment]
> > > > @bkhanal-11 I wonder if you have [installed from src](https://github.com/meta-llama/llama-recipes/tree/main#install-from-source)? and pulled the latest?
> > > 
> > > 
> > > @HamidShojanazeri I followed the exact instruction in the link, but still getting the same error.
> > 
> > 
> > Hi， Have you solved the problem?
> 
> Yeah, I removed `-m` from the instruction code and that seems to have solved the problem.

I have fixed it, thanks!

**Comment by FrankGonzalez07** [comment]
> I see the issue is you are using ` llama-recipes/src/llama_recipes/finetuning.py` which is part of library src code, can you please run`python recipes/finetuning/finetuning.py` instead? that should solve the issue. You can also refer to this [doc](https://github.com/meta-llama/llama-recipes/blob/main/recipes/finetuning/singlegpu_finetuning.md)

Yes, I fixed it by using the following, thanks a lot:
```python
python recipes/finetuning/finetuning.py
```

**Comment by init27** [comment]
Closing as it was solved
